### ISSUE TITLE
Obscurred stats when in default mode

### ISSUE THREAD

**Issue by piotrszymaniec** [maxbourdarie/Path-Of-Exile-Finer-Search-Options#1]
Hey thanks for this useful script, i hope you will develope it as you have plans for. I find it realy useful.

The code for now works great in compact and 2-column compact, but in default mode there is this problem, as in attached picture

![default mode bug](https://user-images.githubusercontent.com/5377285/77845978-227e2b00-71b3-11ea-9454-ecc16357ade2.png)

**Comment by maxbourdarie** [comment]
Hi, 
Glad you like the script ! 
I'll try and release the next features in the next few days
Thanks for bringing the issue to my sight, I don't use the default mode so I would probably never have seen that. 
It's now fixed in version 1.0.5 so feel free to upgrade :)
I also integrated the edits you made in your Fork, thank you for contributing :)
