### ISSUE TITLE
Must Mouse-Hover to have Stats Highlighted

### ISSUE THREAD

**Issue by IeUDE** [maxbourdarie/Path-Of-Exile-Finer-Search-Options#4]
Is this desired?

I would expect that the affixes I have in the search should be highlighted already -- I have to hover with the mouse first to have the affixes highlighted ...

See pic, the yellow highlighted by me, should have been green highlighted -- they are not, only once I hover with the mouse over it, it gets highlighted ...

[<a href="https://ibb.co/nzV7H0z"><img src="https://i.ibb.co/Wgdkb3g/Capture.png" alt="Capture" border="0"></a>](url)

**Comment by maxbourdarie** [comment]
Hi, 

This is desired, I did it for performance reasons. 

Techincally, the script has to parse every mod of the item you hover on, and dispatch css classes accordingly to highlight the ones that are in your filters

By restricting that parsing to the item you hover on, the script does not have to take more ressources than necessary to process everything in the list (the items are loaded by batches of 100 IIRC)

I felt that it was not much of an inconvenience since I usually hover over items that catch my attention in the first place, so the hghlight feature comes in when I need it

Hope I've answered your question, 
regards

**Comment by IeUDE** [comment]
Got it, thank you for the quick response!
